### ISSUE TITLE
it seems nodeID can't be found or attached.

### ISSUE THREAD

**Issue by kunthar** [Nekso/nkcluster#1]
on dev1, dev2, dev3:
> Error in process <0.1315.0> on node 'dev1@127.0.0.1' with exit value: {undef,[{nkdist,find_proc,[{nkcluster,<<4 bytes>>}],[]},{nkcluster_nodes,try_connect,3,[{file,"src/nkcluster_nodes.erl"},{line,373}]}

workers fine:
> 01:34:52.252 [info] Agent connecting to [{nkcluster_protocol,tcp,{127,0,0,1},15003}]
01:34:52.254 [notice] Node 'worker' connected to tcp:127.0.0.1:15003
01:34:52.254 [info] Agent connected
01:35:00.945 [info] Agent sent announcement
01:35:07.254 [notice] Agent ping timeout!

reported part:
``` 
try_connect(NodeId, Connect, Opts) ->
    case nkdist:find_proc({nkcluster, NodeId}) of
        {ok, Pid} ->
            {ok, Pid};
        {error, _} ->
            lager:info("NkCLUSTER launching connection to ~s", [NodeId]),
```

Yosemite 
> Darwin zops1.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

Version 17.5
>  Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

**Comment by kalta** [comment]
Are you sure nkdist is in the path?

**Comment by kunthar** [comment]
Sorry for late reply. Problem seems totally different now. 

https://gist.github.com/kunthar/07d61781ab988896ebe2
```
=WARNING REPORT==== 20-Sep-2015::13:49:16 ===
The on_load function for module eleveldb returned {error,
{load_failed,
"Failed to load NIF library: 'dlopen(deps/eleveldb/priv/eleveldb.so, 2): Symbol not found: __ZNSt8__detail15_List_node_base7_M_hookEPS0_\n  Referenced from: deps/eleveldb/priv/eleveldb.so\n  Expected in: flat namespace\n in deps/eleveldb/priv/eleveldb.so'"}}
```

- i couldn't properly understand if i should use libtool. it seems make handles this. 
https://gist.github.com/kunthar/8d87631f3c07c80cdbac
see lines 352 - 740

**Comment by kalta** [comment]
NkCLUSTER uses currently the last development version of riak_core (which includes the eleveldb library) and it may be broken. I plan to stabilize everything soon...

**Comment by kalta** [comment]
Hi, the branch in master and tag v0.1.0 has fixed riak_core versions.
It works ok for me.

**Comment by kunthar** [comment]
~/development/erlang/nkcluster
 λ kunthar : git tag
v0.1.0
______________________________________________
 ~/development/erlang/nkcluster
 λ kunthar : git co v0.1.0
M	rebar.config
Note: checking out 'v0.1.0'.

HEAD is now at 980418b... Merge branch 'develop'

make clean 
make distclean

https://gist.github.com/kunthar/6cc920798a0361dbed2c

**Comment by kunthar** [comment]
anyone having same issues. check if exist and uninstall related macports specific libs. 
that was the blocker for me. master/tag  fine now.
